name: 울산숙박업 뉴스

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run news script
        run: |
          pip install requests
          python ulsan_news.py
